name: Generate and Deploy Doxygen for Python Code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  doxygen_generation_python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.DOXYGEN_DEPLOY_TOKEN }}
          branch: gh-pages-python
          config_file: ./.github/Doxyfile-python
          doxygen_version: 1.9.6
