name: Doxygen Deployment

on:
  workflow_run:
    workflows:
      - Foxy Docker Build
      - C++ Formatting Check
      - Python Formatting Check
    types:
      - completed

jobs:
  doxygen_generation:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Doxygen for C++
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: ".github/Doxyfile-cpp"

      - name: Generate Doxygen for Python
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: ".github/Doxyfile-python"

      - name: Deploy Doxygen page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs
